# Generated by Django 4.1.7 on 2023-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Email', max_length=20)),
                ('subject_line', models.CharField(max_length=60)),
                ('email_content', models.TextField()),
            ],
        ),
    ]
