# Generated by Django 4.1.7 on 2023-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_amount_billing_date_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
