# Generated by Django 4.1.7 on 2024-01-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
