# Generated by Django 4.1.7 on 2023-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Plan', max_length=50)),
                ('color', models.CharField(max_length=7, null=True)),
                ('price', models.IntegerField(null=True)),
                ('provider', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(max_length=10, null=True)),
            ],
        ),
    ]
