# Generated by Django 4.1.7 on 2023-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(default='New Plan', max_length=50),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='provider',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
