# Generated by Django 4.1.7 on 2023-04-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plans_color_alter_plans_name_alter_plans_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
