# Generated by Django 4.1.7 on 2023-08-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_number', models.CharField(default='00000000', max_length=100)),
                ('ban_name', models.CharField(max_length=100)),
                ('subs_amount', models.IntegerField()),
            ],
        ),
    ]
