# Generated by Django 4.1.7 on 2023-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='four_pin',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='9999999999', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_address',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_city',
            field=models.CharField(default='testland', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_state',
            field=models.CharField(default='MD', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_zip',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
    ]
