# Generated by Django 4.1.7 on 2023-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ship_name',
            new_name='ship_fname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ship_lname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
