# Generated by Django 4.1.7 on 2024-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_ship_name_customuser_ship_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authnet_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
