# Generated by Django 4.1.7 on 2023-07-14 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('auto_sub', models.BooleanField(default=False, null=True)),
                ('esim', models.BooleanField(default=True, null=True)),
                ('imei', models.CharField(default=None, max_length=16, null=True)),
                ('esim_number', models.CharField(default=None, max_length=25)),
                ('amount_owed', models.IntegerField(null=True)),
                ('phone_number', models.CharField(default=None, max_length=15, null=True)),
                ('plan_id', models.ManyToManyField(through='subscriptions.SubPlan', to='plans.plan')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subplan',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
