# Generated by Django 4.1.7 on 2023-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_owed',
            field=models.IntegerField(null=True),
        ),
    ]
