# Generated by Django 4.1.7 on 2023-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_description'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.ManyToManyField(null=True, through='subscriptions.SubPlan', to='plans.plan'),
        ),
    ]
