# Generated by Django 4.1.7 on 2023-06-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_amount_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
