# Generated by Django 4.1.7 on 2023-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_plan_id_delete_subplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
