# Generated by Django 4.1.7 on 2023-08-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_banaccount'),
        ('subscriptions', '0006_subscription_created_at_subscription_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ban_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.banaccount'),
        ),
    ]
