# Generated by Django 4.1.7 on 2023-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_has_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='esim_number',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='imei',
            field=models.CharField(default=None, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
