# Generated by Django 4.1.7 on 2023-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscription_esim_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
