# Generated by Django 4.1.7 on 2023-11-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_banaccount'),
        ('subscriptions', '0012_subscription_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ban_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.banaccount'),
        ),
    ]
