# Generated by Django 4.1.7 on 2023-11-01 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscription_activation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
