# Generated by Django 4.1.7 on 2023-11-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscription_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
