# Generated by Django 4.1.7 on 2024-01-10 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscription_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
