# Generated by Django 4.1.7 on 2024-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_subscription_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
