# Generated by Django 4.1.7 on 2024-01-23 04:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actionables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='address',
            field=models.CharField(default='asd st', max_length=50),
        ),
        migrations.AddField(
            model_name='port',
            name='city',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='port',
            name='former_account',
            field=django_cryptography.fields.encrypt(models.CharField(default='12121212121212', max_length=25)),
        ),
        migrations.AddField(
            model_name='port',
            name='name',
            field=models.CharField(default='john doe', max_length=50),
        ),
        migrations.AddField(
            model_name='port',
            name='ssn_tax',
            field=django_cryptography.fields.encrypt(models.CharField(default='000000000', max_length=9)),
        ),
        migrations.AddField(
            model_name='port',
            name='state',
            field=models.CharField(default='md', max_length=2),
        ),
        migrations.AddField(
            model_name='port',
            name='zip_code',
            field=models.CharField(default='21215', max_length=5),
        ),
    ]
