# Generated by Django 4.1.7 on 2024-01-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_subscription_phone_number'),
        ('actionables', '0002_port_address_port_city_port_former_account_port_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='user_id',
        ),
        migrations.AddField(
            model_name='port',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
