# Generated by Django 4.1.7 on 2024-01-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionables', '0003_remove_port_user_id_port_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_number',
            field=models.CharField(max_length=10),
        ),
    ]
