# Generated by Django 4.1.7 on 2023-07-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_plan_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='plan_ids',
        ),
    ]
